name: conda_env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - conda-forge::r-ggplot2=4.0.1
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-gridextra=2.3
  - conda-forge::r-ordinalnet=2.13
